server:
  port: 8085

mybatis:
  type-aliases-package: com.example.demo.dao.entity
  mapper-locations: classpath:mapper/*.xml
  # 开启二极缓存
  configuration:
    cache-enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb
    username: root
    password: ***
    driver-class-name: com.mysql.cj.jdbc.Driver